In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from PIL import Image
import os
import glob
import math

%matplotlib inline

In [2]:
path = '/home/jaeyeol/Downloads/dir1/data/trainfull/' 

trainimglist = glob.glob(path + '/ref*.jpg')
trainimglist.sort()
trainlabellist = glob.glob(path + '/label.jpg')
trainData = None
trainLabel = None
print ("%d train images" % (len(trainimglist)))
print ("%d train label" % (len(trainlabellist)))



7 train images
1 train label


In [3]:
data = Image.open(trainimglist[0])
row = data.size[0]*data.size[1]

In [4]:
# 모든 밴드의 이미지를 불러 vectorization 후 concatenate.
# [0,0,0,0,0,0,0],[0,0,0,0,0,0,0] 이런식으로 저장

for (f1, i) in zip(trainimglist, range(len(trainimglist))):
    
    img = Image.open(f1)
    
    vec  = np.array(img).reshape(row, 1)/255
                  
    
    if i == 0:
        trainData = vec
    else:
        trainData = np.concatenate((trainData, vec), axis=1)
    
    print trainData.shape 

(61554091, 1)
(61554091, 2)
(61554091, 3)
(61554091, 4)
(61554091, 5)
(61554091, 6)
(61554091, 7)


In [5]:
# trainLabel[i][0]가 1이면 적조 O.
# trainLabel[i][1]가 1이면 적조 X.
img = Image.open(trainlabellist[0])
    
trainLabel = np.array(img).reshape(row, 1)/255                              
trainLabel = np.concatenate((trainLabel, (1-trainLabel)), axis=1)  
print "\n",trainLabel.shape


(61554091, 2)


In [6]:
x = tf.placeholder(tf.float32, [None, 7])
y = tf.placeholder(tf.float32, [None, 2])

W = tf.Variable(tf.truncated_normal([7, 2], stddev=0.1), name='W')
b = tf.Variable(tf.zeros([1,2]),name='b')

saver = tf.train.Saver({'W':W, 'b':b})

In [7]:
hypothesis = tf.nn.sigmoid(tf.add(tf.matmul(x, W), b))

cost = -tf.reduce_mean(y*tf.log(hypothesis) + (1-y)*tf.log(1-hypothesis))

optimizer = tf.train.GradientDescentOptimizer(0.5)

train = optimizer.minimize(cost)

In [8]:
init = tf.global_variables_initializer()

sess = tf.Session()

sess.run(init)

In [9]:
import time


In [10]:
for step in xrange(25):
    start=time.time()
    sess.run(train, feed_dict = {x:trainData, y:trainLabel})
    print step + 1, "Time : ", time.time()-start
    print "cost = ", sess.run(cost, feed_dict = {x:trainData, y:trainLabel})
    print "W", "\n", sess.run(W)
    print "b", "\n", sess.run(b), "\n"

1 Time :  7.67119383812
cost =  0.634752
W 
[[-0.02955659  0.04563994]
 [-0.0583022  -0.02890591]
 [-0.03097332  0.09553545]
 [ 0.10018245 -0.07738239]
 [ 0.05080269  0.15866867]
 [ 0.01623261 -0.13574192]
 [-0.16233991  0.02046356]]
b 
[[-0.12035977  0.12035977]] 

2 Time :  7.66937398911
cost =  0.582289
W 
[[-0.02955659  0.04563994]
 [-0.0583022  -0.02890591]
 [-0.03097332  0.09553545]
 [ 0.10018245 -0.07738239]
 [ 0.05080269  0.15866867]
 [ 0.01623261 -0.13574192]
 [-0.16233991  0.02046356]]
b 
[[-0.23543918  0.23543918]] 

3 Time :  7.76182985306
cost =  0.533936
W 
[[-0.02955659  0.04563994]
 [-0.0583022  -0.02890591]
 [-0.03097332  0.09553545]
 [ 0.10018245 -0.07738239]
 [ 0.05080269  0.15866867]
 [ 0.01623261 -0.13574192]
 [-0.16233991  0.02046356]]
b 
[[-0.34849289  0.34849289]] 

4 Time :  7.4920771122
cost =  0.491583
W 
[[-0.02955659  0.04563994]
 [-0.0583022  -0.02890591]
 [-0.03097332  0.09553545]
 [ 0.10018245 -0.07738239]
 [ 0.05080269  0.15866867]
 [ 0.01623261 -0.1357

In [11]:
testpath = '/home/jaeyeol/Downloads/dir1/data/'

testimglist =  glob.glob(testpath + '/ref*.jpg')

testimglen = len(testimglist)

testData = None

print testimglen

7


In [12]:
data = Image.open(testimglist[0])

row = data.size[0]*data.size[1]

In [13]:


for (f1, i) in zip(testimglist, range(len(testimglist))):
    
    img = Image.open(f1)
    
    vec  = np.array(img).reshape(row, 1)/255
                  
    
    if i == 0:
        testData = vec
    else:
        testData = np.concatenate((testData, vec), axis=1)
    
    print testData.shape

(117649, 1)
(117649, 2)
(117649, 3)
(117649, 4)
(117649, 5)
(117649, 6)
(117649, 7)


In [14]:
testx = tf.placeholder(tf.float32, [None, 7])
testw = tf.placeholder(tf.float32, [None, 2])
testb = tf.placeholder(tf.float32, [None, 2])

hypothesis = tf.nn.sigmoid(tf.add(tf.matmul(testx,testw),testb))

In [15]:
sess.run(W)

array([[-0.02955659,  0.04563994],
       [-0.0583022 , -0.02890591],
       [-0.03097332,  0.09553545],
       [ 0.10018245, -0.07738239],
       [ 0.05080269,  0.15866867],
       [ 0.01623261, -0.13574192],
       [-0.16233991,  0.02046356]], dtype=float32)

In [16]:
result = sess.run([hypothesis], feed_dict={testx:testData, testw:sess.run(W), testb:sess.run(b)})

In [17]:
Infer = None

In [18]:
for i in range(len(testData)):
    testlabel = np.array([np.argmax(result[0][i])])
    if i == 0:
        Infer =testlabel
    else:
        Infer = np.concatenate((Infer, testlabel), axis = 0)

In [19]:
Infer

array([1, 1, 1, ..., 1, 1, 1])

In [20]:
min(Infer)

1